import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { basename, resolve } from 'node:path';
import { chromium, type Browser, type Page } from '@playwright/test';
import { qaReportSchema, researchedLeadSchema, type QaReport, type ResearchedLead } from '../src/schema';
import { evaluateHealthTrustVisual, genericVisualChecks, scoreVisualChecks, visualStatus, type RectMeasurement, type VisualCheck, type VisualMeasurement } from '../src/visual-qa';
import type { HealthTrustArtDirection } from '../src/models';

interface Options { url: string; slug: string; api?: string; token?: string; lead?: string; output: string }
function parseOptions(argv: string[]): Options {
  const value = (name: string) => { const i = argv.indexOf(name); return i >= 0 ? argv[i + 1] : undefined; };
  const url = value('--url'); if (!url) throw new Error('Usage: npm run qa -- --url URL [--slug SLUG] [--lead FILE] [--api URL] [--token TOKEN]');
  const parsed = new URL(url);
  return { url, slug: value('--slug') || parsed.searchParams.get('demo') || parsed.hostname.split('.')[0], api: value('--api') || process.env.DEMO_ENGINE_URL, token: value('--token') || process.env.DEMO_ENGINE_ADMIN_TOKEN, lead: value('--lead'), output: value('--output') || 'qa-output' };
}
const rect = (r: { x:number;y:number;width:number;height:number } | null): RectMeasurement | undefined => r ? { x:r.x,y:r.y,width:r.width,height:r.height } : undefined;
async function visualMeasurement(page: Page, viewport: 'desktop'|'mobile', width:number, height:number): Promise<VisualMeasurement> {
  const get = async (primary:string, fallback:string) => { const p=page.locator(primary).first(); if(await p.count()) return rect(await p.boundingBox()); const b=page.locator(fallback).first(); return await b.count()?rect(await b.boundingBox()):undefined; };
  const artDirection = await page.locator('html').getAttribute('data-art-direction') || undefined;
  const explicit = page.locator('[data-qa="hero-image"] img').first();
  const heroImage = await explicit.count() ? rect(await page.locator('[data-qa="hero-image"]').first().boundingBox()) : (artDirection ? undefined : await get('.hero-media','.hero-media'));
  return { viewport, viewportWidth:width, viewportHeight:height, artDirection, hero:await get('[data-qa="hero"]','.hero'), heroImage, headline:await get('[data-qa="headline"]','.hero h1,.hero-copy h1'), primaryCta:await get('[data-qa="primary-cta"]','[data-primary-cta]'), trustStrip:await get('[data-qa="trust-strip"]','.proof'), services:await get('[data-qa="services"]','.services'), stickyCall:await get('[data-qa="sticky-call"]','.ht-sticky-call') };
}

async function checkViewport(browser:Browser, options:Options, name:'desktop'|'mobile', width:number, height:number, lead?:ResearchedLead) {
  const page=await browser.newPage({viewport:{width,height},deviceScaleFactor:1}); const consoleErrors:string[]=[]; const brokenImages:string[]=[];
  page.on('console',m=>{if(m.type()==='error')consoleErrors.push(m.text().slice(0,1000))}); page.on('pageerror',e=>consoleErrors.push(e.message.slice(0,1000))); page.on('response',r=>{if(r.request().resourceType()==='image'&&!r.ok()&&r.url().startsWith('http'))brokenImages.push(r.url())});
  const response=await page.goto(options.url,{waitUntil:'networkidle',timeout:45000}); const checks:QaReport['viewports'][number]['checks']=[]; const check=(n:string,p:boolean,d?:string)=>checks.push({name:n,passed:p,...(d?{detail:d}:{})});
  check('page_returns_200',response?.status()===200,`HTTP ${response?.status()??'no response'}`); check('title_exists',(await page.title()).trim().length>0); check('no_horizontal_overflow',await page.evaluate(()=>document.documentElement.scrollWidth<=document.documentElement.clientWidth+1),await page.evaluate(()=>`${document.documentElement.scrollWidth}/${document.documentElement.clientWidth}`));
  const primary=page.locator('[data-primary-cta]'); const primaryCount=await primary.count(); check('primary_cta_exists',primaryCount===1,`${primaryCount}`); if(primaryCount){const href=await primary.first().getAttribute('href');check('primary_cta_target_valid',Boolean(href&&!href.startsWith('javascript:')),href||'missing')}
  const bodyText=await page.locator('body').innerText(); check('no_placeholder_markers',!/TODO|Lorem ipsum|zamijeni|placeholder|example\.com/i.test(bodyText)); const empty=await page.locator('main section').evaluateAll(s=>s.filter(x=>!(x.textContent||'').trim()).length);check('no_empty_sections',empty===0,`${empty} empty sections`);
  const brokenAnchors=await page.locator('a[href^="#"]').evaluateAll(a=>a.map(x=>x.getAttribute('href')).filter(h=>h&&h!=='#'&&!document.querySelector(h)));check('navigation_anchors_resolve',brokenAnchors.length===0,brokenAnchors.join(', ')); const headings=await page.locator('main h1,main h2').evaluateAll(h=>h.filter(x=>{const r=x.getBoundingClientRect();return r.width>0&&r.height>0}).length);check('key_content_visible',headings>=3,`${headings} visible headings`);
  if(lead?.publicPhone)check('verified_phone_matches',bodyText.includes(lead.publicPhone),lead.publicPhone);if(lead?.publicEmail)check('verified_email_matches',bodyText.includes(lead.publicEmail),lead.publicEmail); const robots=await page.locator('meta[name="robots"]').getAttribute('content');check('noindex_present',Boolean(robots?.includes('noindex')),robots||'missing');
  const measurement=await visualMeasurement(page,name,width,height); const design=await page.locator('html').getAttribute('data-design-system'); let visualChecks:VisualCheck[];let referenceKey:string|undefined;
  if(design==='health-trust'&&['pet-first','doctor-first','clinic-first'].includes(measurement.artDirection||'')){const d=measurement.artDirection as HealthTrustArtDirection;visualChecks=evaluateHealthTrustVisual(d,measurement);referenceKey=`health-trust/${d}`}else visualChecks=genericVisualChecks(measurement);
  const visualScore=scoreVisualChecks(visualChecks); const dir=resolve(options.output,options.slug);await mkdir(dir,{recursive:true});const screenshotPath=resolve(dir,`${name}.png`);await page.screenshot({path:screenshotPath,fullPage:true});await page.close(); return {viewport:{name,width,height,checks,screenshotKey:undefined as string|undefined},consoleErrors,brokenImages,screenshotPath,visualChecks,visualScore,referenceKey};
}
async function upload(options:Options, viewport:'desktop'|'mobile', path:string){if(!options.api||!options.token)return undefined;const r=await fetch(`${options.api}/__admin/demos/${encodeURIComponent(options.slug)}/screenshots/${viewport}`,{method:'PUT',headers:{Authorization:`Bearer ${options.token}`,'Content-Type':'image/png'},body:await readFile(path)});if(!r.ok)throw new Error(`Screenshot upload ${r.status}: ${await r.text()}`);return (await r.json() as {key:string}).key}
function technicalScore(viewports:QaReport['viewports'],consoleErrors:string[],brokenImages:string[]){const c=viewports.flatMap(v=>v.checks);if(!c.length)return 0;let s=Math.round(c.filter(x=>x.passed).length/c.length*100);if(consoleErrors.length)s-=Math.min(20,consoleErrors.length*5);if(brokenImages.length)s-=Math.min(20,brokenImages.length*5);return Math.max(0,s)}

async function main(){const options=parseOptions(process.argv.slice(2));const lead=options.lead?researchedLeadSchema.parse(JSON.parse(await readFile(resolve(options.lead),'utf8'))):undefined;const browser=await chromium.launch({headless:true});try{const [desktop,mobile]=await Promise.all([checkViewport(browser,options,'desktop',1440,1000,lead),checkViewport(browser,options,'mobile',390,844,lead)]);const [dk,mk]=await Promise.all([upload(options,'desktop',desktop.screenshotPath),upload(options,'mobile',mobile.screenshotPath)]);desktop.viewport.screenshotKey=dk;mobile.viewport.screenshotKey=mk;const consoleErrors=[...desktop.consoleErrors,...mobile.consoleErrors].slice(0,30);const brokenImages=[...new Set([...desktop.brokenImages,...mobile.brokenImages])].slice(0,30);const tech=technicalScore([desktop.viewport,mobile.viewport],consoleErrors,brokenImages);const visual=Math.round((desktop.visualScore+mobile.visualScore)/2);const vstatus=visualStatus(visual);const technicalPassed=tech>=90&&!consoleErrors.length&&!brokenImages.length;const outreachReady=technicalPassed&&vstatus==='passed';const report=qaReportSchema.parse({status:technicalPassed?'passed':'failed',checkedAt:new Date().toISOString(),url:options.url,technicalScore:tech,visualScore:visual,visualStatus:vstatus,referenceKey:desktop.referenceKey||mobile.referenceKey,visualChecks:[...desktop.visualChecks,...mobile.visualChecks],viewports:[desktop.viewport,mobile.viewport],consoleErrors,brokenImages});const reportPath=resolve(options.output,options.slug,'report.json');await writeFile(reportPath,`${JSON.stringify(report,null,2)}\n`,'utf8');if(options.api&&options.token){const r=await fetch(`${options.api}/__admin/demos/${encodeURIComponent(options.slug)}/qa`,{method:'PATCH',headers:{Authorization:`Bearer ${options.token}`,'Content-Type':'application/json'},body:JSON.stringify(report)});if(!r.ok)throw new Error(`QA report API ${r.status}: ${await r.text()}`)}process.stdout.write(`${JSON.stringify({ok:outreachReady,technicalScore:tech,visualScore:visual,visualStatus:vstatus,report:basename(reportPath),screenshots:[desktop.screenshotPath,mobile.screenshotPath]},null,2)}\n`);if(!outreachReady)process.exitCode=1}finally{await browser.close()}}
main().catch((e:unknown)=>{process.stderr.write(`${e instanceof Error?e.message:String(e)}\n`);process.exitCode=1});
