import { ZodError } from 'zod';
import { attachCustomDomain, detachCustomDomain } from './cloudflare-domains';
import { dashboardHeaders, renderDashboard } from './dashboard-v2';
import { ApiError, errorResponse, isAuthorized, json, parsePositiveInt, readBodyBytes, readJsonBody } from './http';
import type { DemoEventType, DemoRow, LeadRow, RuntimeEnv } from './models';
import { MAX_ADMIN_BODY_BYTES, MAX_SCREENSHOT_BYTES, createDemoSchema, createLeadSchema, demoContentSchema, qaReportSchema, slugSchema } from './schema';
import { isOutreachReady } from './visual-qa';
import { pageHeaders, renderDemo, renderNotFound } from './templates-v2';

export const RESERVED_SUBDOMAINS = new Set(['www','api','mail','smtp','ftp','admin','app','cdn','assets','kids','animationstudios','sales','status','support','demo']);
const EVENT_TYPES = new Set<DemoEventType>(['page_view','primary_cta_click','secondary_cta_click','phone_click','email_click']);

const handler = {
  async fetch(request: Request, env: RuntimeEnv, ctx: ExecutionContext): Promise<Response> {
    const requestId=crypto.randomUUID();const url=new URL(request.url);
    try {
      if(url.pathname==='/__health')return json({ok:true,service:env.WORKER_SERVICE,version:'health-trust-v2',now:new Date().toISOString(),requestId});
      if(url.pathname==='/__admin'||url.pathname==='/__admin/'){const nonce=crypto.randomUUID().replaceAll('-','');return new Response(renderDashboard(nonce),{headers:dashboardHeaders(nonce)})}
      if(url.pathname.startsWith('/__admin/'))return await handleAdmin(request,env,requestId);
      if(url.pathname==='/__event')return await handleTrackedRedirect(request,env);
      return await handlePublicDemo(request,env,ctx);
    } catch(error){return errorResponse(error,requestId)}
  },
  async scheduled(_controller:ScheduledController,env:RuntimeEnv,ctx:ExecutionContext):Promise<void>{ctx.waitUntil(cleanupExpired(env))},
} satisfies ExportedHandler<RuntimeEnv>;
export default handler;

async function handlePublicDemo(request:Request,env:RuntimeEnv,ctx:ExecutionContext):Promise<Response>{
  const slug=resolveSlug(new URL(request.url),env.ROOT_DOMAIN);if(!slug)return notFound('Demo nije pronađen.');
  const demo=await getDemoBySlug(env,slug);if(!demo||demo.status!=='active')return notFound('Demo nije pronađen ili više nije aktivan.');
  if(isExpired(demo.expires_at)){ctx.waitUntil(expireDemo(env,demo));return notFound('Ovaj demo je istekao.')}
  let stored:unknown;try{stored=JSON.parse(demo.content_json)}catch{stored=null}const parsed=demoContentSchema.safeParse(stored);
  if(!parsed.success){console.error(JSON.stringify({event:'invalid_stored_demo',demoId:demo.id,issues:parsed.error.issues}));return new Response(renderNotFound('Sadržaj demo stranice trenutačno nije dostupan.'),{status:500,headers:pageHeaders()})}
  ctx.waitUntil(recordEvent(env,demo.id,'page_view',request));return new Response(renderDemo(demo,parsed.data),{headers:pageHeaders()});
}

async function handleAdmin(request:Request,env:RuntimeEnv,requestId:string):Promise<Response>{
  if(!await isAuthorized(request,env.ADMIN_TOKEN))throw new ApiError(401,'UNAUTHORIZED','Nedostaje valjan admin token.');const url=new URL(request.url);
  if(request.method==='GET'&&url.pathname==='/__admin/leads')return listLeads(env);if(request.method==='POST'&&url.pathname==='/__admin/leads')return createLead(request,env);
  const la=url.pathname.match(/^\/__admin\/leads\/(\d+)\/(approve|reject)$/);if(request.method==='POST'&&la)return updateLeadDecision(env,Number(la[1]),la[2] as 'approve'|'reject');
  if(request.method==='GET'&&url.pathname==='/__admin/demos')return listDemos(request,env);if(request.method==='POST'&&url.pathname==='/__admin/demos')return createDemo(request,env,requestId);
  const shot=url.pathname.match(/^\/__admin\/demos\/([a-z0-9-]+)\/screenshots\/(desktop|mobile)$/);if(request.method==='PUT'&&shot)return uploadScreenshot(request,env,shot[1],shot[2] as 'desktop'|'mobile');
  const qa=url.pathname.match(/^\/__admin\/demos\/([a-z0-9-]+)\/qa$/);if(request.method==='PATCH'&&qa)return updateQa(request,env,qa[1]);
  const da=url.pathname.match(/^\/__admin\/demos\/([a-z0-9-]+)\/(approve|regenerate)$/);if(request.method==='POST'&&da)return updateDemoWorkflow(env,da[1],da[2] as 'approve'|'regenerate');
  const demo=url.pathname.match(/^\/__admin\/demos\/([a-z0-9-]+)$/);if(request.method==='DELETE'&&demo)return archiveDemo(env,demo[1]);
  const asset=url.pathname.match(/^\/__admin\/assets\/(.+)$/);if(request.method==='GET'&&asset)return getAsset(env,decodeURIComponent(asset[1]));
  throw new ApiError(404,'ADMIN_ROUTE_NOT_FOUND','Admin ruta ne postoji.');
}
async function listLeads(env:RuntimeEnv){const r=await env.DB.prepare(`SELECT * FROM leads ORDER BY CASE status WHEN 'approved_for_demo' THEN 0 WHEN 'researched' THEN 1 WHEN 'new' THEN 2 ELSE 3 END, score DESC, created_at DESC LIMIT 250`).all<LeadRow>();return json({ok:true,leads:r.results})}
async function createLead(request:Request,env:RuntimeEnv){const i=parseSchema(createLeadSchema,await readJsonBody(request,MAX_ADMIN_BODY_BYTES));assertSlugAllowed(i.slug);try{const r=await env.DB.prepare(`INSERT INTO leads (business_name,slug,website_url,google_business_url,instagram_url,facebook_url,public_email,public_phone,city,industry,source,score,score_reasons_json,research_json,status,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP) RETURNING *`).bind(i.businessName,i.slug,i.websiteUrl??null,i.googleBusinessUrl??null,i.instagramUrl??null,i.facebookUrl??null,i.publicEmail??null,i.publicPhone??null,i.city??null,i.industry,i.source,i.score,JSON.stringify(i.scoreReasons),JSON.stringify(i),i.status).first<LeadRow>();return json({ok:true,lead:r},201)}catch(e){if(String(e).includes('UNIQUE'))throw new ApiError(409,'LEAD_SLUG_EXISTS','Lead s ovim slugom već postoji.');throw e}}
async function updateLeadDecision(env:RuntimeEnv,id:number,action:'approve'|'reject'){const status=action==='approve'?'approved_for_demo':'rejected';const r=await env.DB.prepare(`UPDATE leads SET status=?,updated_at=CURRENT_TIMESTAMP WHERE id=? RETURNING *`).bind(status,id).first<LeadRow>();if(!r)throw new ApiError(404,'LEAD_NOT_FOUND','Lead nije pronađen.');await workflow(env,r.id,null,action==='approve'?'lead_approved_for_demo':'lead_rejected',{},false);return json({ok:true,lead:r})}
async function listDemos(request:Request,env:RuntimeEnv){const r=await env.DB.prepare(`SELECT * FROM demos ORDER BY created_at DESC LIMIT 250`).all<DemoRow>();const origin=new URL(request.url).origin;return json({ok:true,demos:r.results.map(d=>({...d,art_direction:d.design_system_key==='health-trust'?(d.art_direction||'pet-first'):null,visual_qa_status:d.visual_qa_status||'pending',preview_url:d.custom_domain_id?`https://${d.slug}.${env.ROOT_DOMAIN}`:`${origin}/?demo=${d.slug}`}))})}

async function createDemo(request:Request,env:RuntimeEnv,requestId:string):Promise<Response>{
  const i=parseSchema(createDemoSchema,await readJsonBody(request,MAX_ADMIN_BODY_BYTES));assertSlugAllowed(i.slug);const key=normalizeIdempotencyKey(request.headers.get('idempotency-key'));const hash=key?await sha256(JSON.stringify(i)):null;
  if(key){const replay=await env.DB.prepare(`SELECT * FROM demos WHERE idempotency_key=? LIMIT 1`).bind(key).first<DemoRow>();if(replay){if(replay.idempotency_hash!==hash)throw new ApiError(409,'IDEMPOTENCY_KEY_REUSED','Idempotency-Key je već korišten za drugi payload.');return createdResponse(request,env,replay,true)}}
  if(await getDemoBySlug(env,i.slug))throw new ApiError(409,'DEMO_SLUG_EXISTS','Demo s ovim slugom već postoji. Arhivirajte ga ili odaberite novi slug.');if(i.leadId){const lead=await env.DB.prepare(`SELECT id FROM leads WHERE id=? LIMIT 1`).bind(i.leadId).first();if(!lead)throw new ApiError(404,'LEAD_NOT_FOUND','Povezani lead nije pronađen.')}
  const now=new Date();const days=parsePositiveInt(env.DEFAULT_EXPIRY_DAYS,7,30);const expires=i.expiresAt?new Date(i.expiresAt):new Date(now.getTime()+(i.expiresInDays??days)*86400000);if(!Number.isFinite(expires.getTime())||expires<=now)throw new ApiError(400,'INVALID_EXPIRY','Datum isteka mora biti u budućnosti.');
  if(i.attachDomain){const a=await env.DB.prepare(`SELECT COUNT(*) AS total FROM demos WHERE status='active' AND custom_domain_id IS NOT NULL`).first<{total:number}>();const ceiling=parsePositiveInt(env.ACTIVE_DOMAIN_LIMIT,80,99);if((a?.total??0)>=ceiling)throw new ApiError(409,'DOMAIN_POOL_NEAR_CAPACITY',`Aktivni domain pool dosegnuo je operativni limit ${ceiling}.`)}
  let created:DemoRow|null=null;let domain:string|null=null;try{const art=i.designSystemKey==='health-trust'?(i.artDirection??'pet-first'):null;created=await env.DB.prepare(`INSERT INTO demos (slug,business_name,template_key,content_json,source_url,lead_email,status,custom_domain_id,created_at,updated_at,expires_at,lead_id,design_system_key,generation_version,qa_status,idempotency_key,idempotency_hash,outreach_json,art_direction,art_direction_reason,technical_score,visual_score,visual_qa_status) VALUES (?,?,?,?,?,?,'active',NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,?,?,?,?,'pending',?,?,?,?,?,NULL,NULL,'pending') RETURNING *`).bind(i.slug,i.businessName,i.designSystemKey,JSON.stringify(i.content),i.sourceUrl??null,i.leadEmail??null,expires.toISOString(),i.leadId??null,i.designSystemKey,i.generationVersion,key,hash,JSON.stringify(i.outreach),art,i.artDirectionReason??null).first<DemoRow>();if(!created)throw new ApiError(500,'DEMO_CREATE_FAILED','D1 nije vratio kreirani demo.');if(i.attachDomain){domain=await attachCustomDomain(env,`${i.slug}.${env.ROOT_DOMAIN}`);created.custom_domain_id=domain;await env.DB.prepare(`UPDATE demos SET custom_domain_id=?,updated_at=CURRENT_TIMESTAMP WHERE id=?`).bind(domain,created.id).run()}if(i.leadId)await env.DB.prepare(`UPDATE leads SET status='demo_ready',updated_at=CURRENT_TIMESTAMP WHERE id=?`).bind(i.leadId).run();await workflow(env,i.leadId??null,created.id,'demo_created',{requestId,artDirection:art,artDirectionReason:i.artDirectionReason??null},false);return createdResponse(request,env,created,false)}catch(e){if(created&&domain){try{await detachCustomDomain(env,domain)}catch(re){await env.DB.prepare(`UPDATE demos SET custom_domain_id=? WHERE id=?`).bind(domain,created.id).run();console.error(re);throw new ApiError(502,'DOMAIN_ROLLBACK_FAILED','Attach nije dovršen, a domena nije mogla biti automatski odvojena.')}}if(created)await env.DB.prepare(`DELETE FROM demos WHERE id=? AND custom_domain_id IS NULL`).bind(created.id).run();throw e}}
function createdResponse(request:Request,env:RuntimeEnv,d:DemoRow,replayed:boolean){const origin=new URL(request.url).origin;return json({ok:true,replayed,demo:{id:d.id,slug:d.slug,businessName:d.business_name,url:d.custom_domain_id?`https://${d.slug}.${env.ROOT_DOMAIN}`:`${origin}/?demo=${d.slug}`,expiresAt:d.expires_at,customDomainId:d.custom_domain_id,qaStatus:d.qa_status,artDirection:d.art_direction??(d.design_system_key==='health-trust'?'pet-first':null),artDirectionReason:d.art_direction_reason??null,technicalScore:d.technical_score??null,visualScore:d.visual_score??null}},replayed?200:201)}

async function updateQa(request:Request,env:RuntimeEnv,slug:string){const report=parseSchema(qaReportSchema,await readJsonBody(request,MAX_ADMIN_BODY_BYTES));const dk=report.viewports.find(v=>v.name==='desktop')?.screenshotKey??null;const mk=report.viewports.find(v=>v.name==='mobile')?.screenshotKey??null;const pass=isOutreachReady(report.technicalScore,report.visualScore,report.visualStatus);const qs=pass?'passed':'failed';const vs=report.visualStatus==='passed'?'passed':'needs_visual_review';const d=await env.DB.prepare(`UPDATE demos SET qa_status=?,qa_report_json=?,technical_score=?,visual_score=?,visual_qa_status=?,desktop_screenshot_key=COALESCE(?,desktop_screenshot_key),mobile_screenshot_key=COALESCE(?,mobile_screenshot_key),approved_at=NULL,updated_at=CURRENT_TIMESTAMP WHERE slug=? AND status='active' RETURNING *`).bind(qs,JSON.stringify({...report,status:qs}),report.technicalScore,report.visualScore,vs,dk,mk,slug).first<DemoRow>();if(!d)throw new ApiError(404,'DEMO_NOT_FOUND','Aktivni demo nije pronađen.');await workflow(env,d.lead_id,d.id,pass?'demo_qa_passed':'demo_qa_failed',{technicalScore:report.technicalScore,visualScore:report.visualScore,visualStatus:report.visualStatus},false);return json({ok:true,demo:d,outreachReady:pass})}
async function uploadScreenshot(request:Request,env:RuntimeEnv,slug:string,viewport:'desktop'|'mobile'){if(request.headers.get('content-type')!=='image/png')throw new ApiError(415,'SCREENSHOT_TYPE_INVALID','Screenshot mora biti PNG.');if(Number(request.headers.get('content-length')??0)>MAX_SCREENSHOT_BYTES)throw new ApiError(413,'SCREENSHOT_TOO_LARGE','Screenshot je veći od 8 MB.');const d=await getDemoBySlug(env,slug);if(!d||d.status!=='active')throw new ApiError(404,'DEMO_NOT_FOUND','Aktivni demo nije pronađen.');const bytes=await readBodyBytes(request,MAX_SCREENSHOT_BYTES);if(!bytes.byteLength)throw new ApiError(400,'SCREENSHOT_EMPTY','Screenshot tijelo je prazno.');const key=`screenshots/${d.id}/${viewport}-${Date.now()}.png`;const stored=await env.ASSETS.put(key,bytes,{httpMetadata:{contentType:'image/png',cacheControl:'private, max-age=31536000, immutable'},customMetadata:{demoId:String(d.id),slug:d.slug,viewport}});if(!stored)throw new ApiError(500,'SCREENSHOT_STORE_FAILED','R2 nije spremio screenshot.');const col=viewport==='desktop'?'desktop_screenshot_key':'mobile_screenshot_key';await env.DB.prepare(`UPDATE demos SET ${col}=?,updated_at=CURRENT_TIMESTAMP WHERE id=?`).bind(key,d.id).run();return json({ok:true,key},201)}
async function getAsset(env:RuntimeEnv,key:string){if(!/^screenshots\/\d+\/(desktop|mobile)-\d+\.png$/.test(key))throw new ApiError(400,'ASSET_KEY_INVALID','Asset ključ nije valjan.');const o=await env.ASSETS.get(key);if(!o||!('body'in o))throw new ApiError(404,'ASSET_NOT_FOUND','Asset nije pronađen.');const h=new Headers({'Cache-Control':'private, max-age=300',ETag:o.httpEtag});o.writeHttpMetadata(h);return new Response(o.body,{headers:h})}
async function updateDemoWorkflow(env:RuntimeEnv,slug:string,action:'approve'|'regenerate'){const d=await getDemoBySlug(env,slug);if(!d||d.status!=='active')throw new ApiError(404,'DEMO_NOT_FOUND','Aktivni demo nije pronađen.');if(action==='approve'){const t=d.technical_score??0,v=d.visual_score??0,s=d.visual_qa_status??'pending';if(d.qa_status!=='passed'||!isOutreachReady(t,v,s))throw new ApiError(409,'VISUAL_QA_NOT_PASSED',`Demo nije spreman za outreach (technical ${t}/100, visual ${v}/100).`);await env.DB.batch([env.DB.prepare(`UPDATE demos SET approved_at=CURRENT_TIMESTAMP,updated_at=CURRENT_TIMESTAMP WHERE id=?`).bind(d.id),env.DB.prepare(`INSERT INTO workflow_events (lead_id,demo_id,event_type,payload_json,requires_human_action) VALUES (?,?,'demo_approved_for_outreach',?,1)`).bind(d.lead_id,d.id,d.outreach_json??'{}')]);return json({ok:true,event:'demo_approved_for_outreach',emailSent:false})}await env.DB.batch([env.DB.prepare(`UPDATE demos SET qa_status='pending',qa_report_json=NULL,technical_score=NULL,visual_score=NULL,visual_qa_status='pending',approved_at=NULL,updated_at=CURRENT_TIMESTAMP WHERE id=?`).bind(d.id),env.DB.prepare(`INSERT INTO workflow_events (lead_id,demo_id,event_type,payload_json,requires_human_action) VALUES (?,?,'demo_regeneration_requested',?,0)`).bind(d.lead_id,d.id,JSON.stringify({artDirection:d.art_direction}))]);return json({ok:true,event:'demo_regeneration_requested',artDirection:d.art_direction},202)}
async function archiveDemo(env:RuntimeEnv,slug:string){const d=await getDemoBySlug(env,slug);if(!d)throw new ApiError(404,'DEMO_NOT_FOUND','Demo nije pronađen.');if(d.custom_domain_id)await detachCustomDomain(env,d.custom_domain_id);await env.DB.prepare(`UPDATE demos SET status='archived',custom_domain_id=NULL,updated_at=CURRENT_TIMESTAMP WHERE id=?`).bind(d.id).run();await workflow(env,d.lead_id,d.id,'demo_archived',{},false);return json({ok:true,slug,status:'archived'})}
async function handleTrackedRedirect(request:Request,env:RuntimeEnv){const u=new URL(request.url);const slug=normalizeSlug(u.searchParams.get('demo')??resolveSlug(u,env.ROOT_DOMAIN)??'');const type=u.searchParams.get('type') as DemoEventType|null;const target=safeRedirectTarget(u.searchParams.get('to')??'#kontakt');if(!slug||!type||type==='page_view'||!EVENT_TYPES.has(type))throw new ApiError(400,'EVENT_INVALID','Tracking event nije valjan.');const d=await getDemoBySlug(env,slug);if(!d||d.status!=='active'||isExpired(d.expires_at))throw new ApiError(404,'DEMO_NOT_FOUND','Aktivni demo nije pronađen.');await recordEvent(env,d.id,type,request);return Response.redirect(target.startsWith('#')?`${u.origin}/?demo=${encodeURIComponent(slug)}${target}`:target,302)}
function safeRedirectTarget(v:string){if(v.startsWith('#'))return v;if(/^(tel:|mailto:)/i.test(v)&&!/["'<>`\s]/.test(v))return v;try{const u=new URL(v);return u.protocol==='https:'||u.protocol==='http:'?u.href:'#kontakt'}catch{return'#kontakt'}}
async function recordEvent(env:RuntimeEnv,id:number,type:DemoEventType,request:Request){const u=new URL(request.url);const s=[env.DB.prepare(`INSERT INTO demo_events (demo_id,event_type,path,referrer,country,user_agent) VALUES (?,?,?,?,?,?)`).bind(id,type,u.pathname,request.headers.get('referer'),request.headers.get('cf-ipcountry'),request.headers.get('user-agent'))];if(type==='page_view')s.push(env.DB.prepare(`UPDATE demos SET view_count=view_count+1,first_viewed_at=COALESCE(first_viewed_at,CURRENT_TIMESTAMP),last_viewed_at=CURRENT_TIMESTAMP,updated_at=CURRENT_TIMESTAMP WHERE id=?`).bind(id));await env.DB.batch(s)}
async function cleanupExpired(env:RuntimeEnv){const r=await env.DB.prepare(`SELECT * FROM demos WHERE status='active' AND expires_at IS NOT NULL AND expires_at<=? ORDER BY expires_at ASC LIMIT 100`).bind(new Date().toISOString()).all<DemoRow>();for(const d of r.results){try{await expireDemo(env,d)}catch(e){console.error(JSON.stringify({event:'expiry_failed',demoId:d.id,error:e instanceof Error?e.message:String(e)}))}}}
async function expireDemo(env:RuntimeEnv,d:DemoRow){if(d.custom_domain_id)await detachCustomDomain(env,d.custom_domain_id);await env.DB.batch([env.DB.prepare(`UPDATE demos SET status='expired',custom_domain_id=NULL,updated_at=CURRENT_TIMESTAMP WHERE id=?`).bind(d.id),env.DB.prepare(`INSERT INTO workflow_events (lead_id,demo_id,event_type,payload_json,requires_human_action) VALUES (?,?,'demo_expired','{}',0)`).bind(d.lead_id,d.id)])}
async function workflow(env:RuntimeEnv,lead:number|null,demo:number|null,event:string,payload:unknown,human:boolean){await env.DB.prepare(`INSERT INTO workflow_events (lead_id,demo_id,event_type,payload_json,requires_human_action) VALUES (?,?,?,?,?)`).bind(lead,demo,event,JSON.stringify(payload),human?1:0).run()}
async function getDemoBySlug(env:RuntimeEnv,slug:string){return env.DB.prepare(`SELECT * FROM demos WHERE slug=? LIMIT 1`).bind(slug).first<DemoRow>()}
function parseSchema<T>(schema:{parse(value:unknown):T},value:unknown):T{try{return schema.parse(value)}catch(e){if(e instanceof ZodError)throw new ApiError(422,'VALIDATION_FAILED','Payload nije prošao validaciju.',e.issues.map(i=>({path:i.path.join('.'),message:i.message})));throw e}}
function normalizeIdempotencyKey(v:string|null){if(!v)return null;const n=v.trim();if(!/^[A-Za-z0-9._:-]{8,128}$/.test(n))throw new ApiError(400,'IDEMPOTENCY_KEY_INVALID','Idempotency-Key mora imati 8–128 sigurnih znakova.');return n}
function assertSlugAllowed(slug:string){if(RESERVED_SUBDOMAINS.has(slug))throw new ApiError(400,'SLUG_RESERVED','Slug je rezerviran i ne može se koristiti.')}
export function resolveSlug(url:URL,rootDomain:string):string|null{const h=url.hostname.toLowerCase(),suffix=`.${rootDomain.toLowerCase()}`;if(h.endsWith(suffix)){const sub=h.slice(0,-suffix.length);if(!sub.includes('.')&&!RESERVED_SUBDOMAINS.has(sub))return normalizeSlug(sub)||null}if(h==='localhost'||h==='127.0.0.1'||h.endsWith('.workers.dev')){const p=normalizeSlug(url.searchParams.get('demo')??'');return p&&!RESERVED_SUBDOMAINS.has(p)?p:null}return null}
export function normalizeSlug(value:string){const r=slugSchema.safeParse(value);return r.success?r.data:''}
export function isExpired(value:string|null,now=Date.now()){return Boolean(value&&Number.isFinite(new Date(value).getTime())&&new Date(value).getTime()<=now)}
async function sha256(v:string){const d=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(v));return Array.from(new Uint8Array(d),b=>b.toString(16).padStart(2,'0')).join('')}
function notFound(message:string){return new Response(renderNotFound(message),{status:404,headers:pageHeaders()})}
