const buildPackagesHr = [
  {
    id: "basic",
    name: "Web Basic",
    price: 300,
    payment: "jednokratno",
    description: "Za obrte i male tvrtke kojima treba jednostavna, moderna i profesionalna web-stranica.",
    included: [
      "moderna one-page web-stranica",
      "do 5 sadržajnih sekcija",
      "naslovna prezentacija",
      "prikaz osnovnih usluga",
      "sekcija o tvrtki ili obrtu",
      "kontaktni podaci",
      "Google karta",
      "gumbi za telefonski poziv, e-mail ili WhatsApp",
      "responzivan prikaz za mobitele, tablete i računala",
      "napredna tehnička i on-page SEO optimizacija",
      "Google Search Console",
      "osnovna analitika posjeta",
      "povezivanje domene",
      "objava web-stranice",
      "jedan krug dorada",
    ],
    note: "Klijent dostavlja tekstove, fotografije i logotip.",
  },
  {
    id: "business",
    name: "Web Business",
    price: 500,
    payment: "jednokratno",
    badge: "Najbolji omjer cijene i koristi",
    featured: true,
    description: "Za tvrtke koje žele ozbiljniju prezentaciju, više sadržaja i kvalitetniju pripremu za upite potencijalnih klijenata.",
    included: [
      "sve iz paketa Web Basic",
      "do 5 zasebnih podstranica ili sadržajno proširena one-page stranica",
      "detaljniji prikaz usluga ili paketa",
      "galerija fotografija",
      "kontaktni obrazac ili standardna lead forma",
      "Google karta i prošireni kontaktni blok",
      "napredna tehnička i on-page SEO optimizacija",
      "optimizirani SEO naslovi i meta opisi",
      "pravilna hijerarhija naslova i struktura sadržaja",
      "Google Search Console",
      "Google Analytics ili druga osnovna analitika",
      "praćenje klikova na poziv, WhatsApp i obrazac kada je tehnički moguće",
      "optimizacija brzine i osnovni Core Web Vitals pregled",
      "pomoć pri strukturiranju dostavljenog sadržaja",
      "pravne stranice prema pripremljenom predlošku",
      "dva kruga dorada",
    ],
  },
  {
    id: "pro",
    name: "Web Pro",
    price: 700,
    payment: "jednokratno",
    description: "Za tvrtke kojima je web važan prodajni kanal i koje žele napredniju SEO strukturu, ciljane podstranice i funkcionalnosti prilagođene poslovanju.",
    included: [
      "sve iz paketa Web Business",
      "do 8 podstranica",
      "do 3 ciljane SEO landing stranice",
      "istraživanje relevantnih ključnih pojmova",
      "napredna sadržajna i SEO arhitektura",
      "napredna tehnička i on-page SEO optimizacija",
      "prilagođeni lead ili kontaktni obrazac",
      "mogućnost generiranja WhatsApp ili e-mail upita",
      "detaljni prikaz usluga, procesa, referenci ili projekata",
      "prošireni FAQ",
      "strukturirani podaci gdje su primjenjivi",
      "naprednije praćenje konverzija",
      "optimizacija brzine i korisničkog iskustva",
      "pomoć pri uređivanju, strukturiranju i skraćivanju tekstova",
      "tri kruga dorada",
    ],
    project: {
      label: "Primjer Web Pro projekta: Auto Gubić",
      cta: "Pogledaj projekt",
      href: "https://autogubic.hr/",
    },
  },
];

const buildPackagesEn = [
  {
    id: "basic",
    name: "Web Basic",
    price: 300,
    payment: "one-time",
    description: "For trades and small businesses that need a simple, modern, and professional website.",
    included: [
      "modern one-page website",
      "up to 5 content sections",
      "homepage presentation",
      "overview of core services",
      "company or business profile section",
      "contact details",
      "Google map",
      "call, email, or WhatsApp buttons",
      "responsive layout for phones, tablets, and computers",
      "advanced technical and on-page SEO optimization",
      "Google Search Console",
      "basic visit analytics",
      "domain connection",
      "website launch",
      "one revision round",
    ],
    note: "The client provides copy, photographs, and a logo.",
  },
  {
    id: "business",
    name: "Web Business",
    price: 500,
    payment: "one-time",
    badge: "Best value",
    featured: true,
    description: "For companies that need a stronger presentation, more content, and better preparation for potential customer inquiries.",
    included: [
      "everything in Web Basic",
      "up to 5 separate pages or an expanded one-page website",
      "detailed service or package presentation",
      "photo gallery",
      "contact form or standard lead form",
      "Google map and expanded contact block",
      "advanced technical and on-page SEO optimization",
      "optimized SEO titles and meta descriptions",
      "proper heading hierarchy and content structure",
      "Google Search Console",
      "Google Analytics or another basic analytics tool",
      "call, WhatsApp, and form click tracking where technically possible",
      "speed optimization and a basic Core Web Vitals review",
      "help structuring the supplied content",
      "legal pages based on a prepared template",
      "two revision rounds",
    ],
  },
  {
    id: "pro",
    name: "Web Pro",
    price: 700,
    payment: "one-time",
    description: "For companies that treat their website as an important sales channel and need advanced SEO structure, targeted pages, and business-specific functionality.",
    included: [
      "everything in Web Business",
      "up to 8 pages",
      "up to 3 targeted SEO landing pages",
      "relevant keyword research",
      "advanced content and SEO architecture",
      "advanced technical and on-page SEO optimization",
      "custom lead or contact form",
      "structured WhatsApp or email inquiry generation",
      "detailed services, process, references, or project presentation",
      "expanded FAQ",
      "structured data where applicable",
      "advanced conversion tracking",
      "speed and user experience optimization",
      "help editing, structuring, and shortening copy",
      "three revision rounds",
    ],
    project: {
      label: "Web Pro project example: Auto Gubić",
      cta: "View project",
      href: "https://autogubic.hr/",
    },
  },
];

const maintenanceHr = [
  {
    id: "maintenance-basic",
    name: "Održavanje Basic",
    price: 200,
    payment: "godišnje",
    included: [
      "hosting web-stranice",
      "Cloudflare infrastruktura",
      "DNS upravljanje",
      "SSL certifikat",
      "CDN i osnovna zaštita",
      "nadzor dostupnosti",
      "sigurnosna i tehnička ažuriranja",
      "redoviti backup",
      "otklanjanje grešaka nastalih radom postojećeg sustava",
      "Google Search Console",
      "praćenje indeksiranja",
      "tehnička podrška e-mailom",
    ],
    note: "Ne uključuje redovite izmjene sadržaja.",
  },
  {
    id: "maintenance-business",
    name: "Održavanje Business",
    price: 400,
    payment: "godišnje",
    badge: "Najčešći izbor",
    featured: true,
    included: [
      "sve iz paketa Održavanje Basic",
      "administracija sadržaja",
      "do 12 manjih izmjena godišnje",
      "izmjene postojećih tekstova, fotografija, cijena, kontakata i radnog vremena",
      "redovita provjera kontaktnih obrazaca",
      "praćenje indeksiranja i tehničkih problema u Google Search Consoleu",
      "osnovno održavanje Google Analytics postavki",
      "ažuriranje SEO naslova i meta opisa postojećih stranica",
      "povremena optimizacija brzine",
      "prioritetnija podrška",
    ],
  },
  {
    id: "maintenance-pro",
    name: "Održavanje Pro",
    price: 600,
    payment: "godišnje",
    included: [
      "sve iz paketa Održavanje Business",
      "do 24 manje izmjene godišnje",
      "prioritetna tehnička podrška",
      "održavanje naprednijih obrazaca i postojećih integracija",
      "unos novih usluga, projekata, referenci ili članova tima",
      "praćenje tehničkog SEO-a",
      "praćenje indeksiranja i ključnih problema u Google Search Consoleu",
      "periodična provjera brzine i Core Web Vitals pokazatelja",
      "godišnji pregled analitike i Search Console podataka",
      "godišnje preporuke za daljnje poboljšanje stranice",
      "manja poboljšanja postojećih sekcija i komponenti",
    ],
  },
];

const maintenanceEn = [
  {
    id: "maintenance-basic",
    name: "Maintenance Basic",
    price: 200,
    payment: "per year",
    included: [
      "website hosting",
      "Cloudflare infrastructure",
      "DNS management",
      "SSL certificate",
      "CDN and basic protection",
      "uptime monitoring",
      "security and technical updates",
      "regular backups",
      "fixes for faults caused by the existing system",
      "Google Search Console",
      "indexing monitoring",
      "technical support by email",
    ],
    note: "Does not include regular content changes.",
  },
  {
    id: "maintenance-business",
    name: "Maintenance Business",
    price: 400,
    payment: "per year",
    badge: "Most common choice",
    featured: true,
    included: [
      "everything in Maintenance Basic",
      "content administration",
      "up to 12 minor changes per year",
      "updates to existing copy, photos, prices, contacts, and opening hours",
      "regular contact form checks",
      "indexing and technical issue monitoring in Google Search Console",
      "basic Google Analytics settings maintenance",
      "updates to SEO titles and meta descriptions on existing pages",
      "occasional speed optimization",
      "higher-priority support",
    ],
  },
  {
    id: "maintenance-pro",
    name: "Maintenance Pro",
    price: 600,
    payment: "per year",
    included: [
      "everything in Maintenance Business",
      "up to 24 minor changes per year",
      "priority technical support",
      "maintenance of advanced forms and existing integrations",
      "entry of new services, projects, references, or team members",
      "technical SEO monitoring",
      "indexing and key issue monitoring in Google Search Console",
      "periodic speed and Core Web Vitals checks",
      "annual analytics and Search Console review",
      "annual recommendations for further website improvement",
      "minor improvements to existing sections and components",
    ],
  },
];

const additionalHr = [
  ["Dodatna podstranica", "od 80 €"],
  ["Ciljana SEO landing stranica", "od 100 €"],
  ["Redizajn postojeće web-stranice", "od 400 €"],
  ["Google Business profil i osnovno podešavanje", "od 100 €"],
  ["Dodatna administracija sadržaja", "40 €/sat"],
  ["AI chatbot ili AI integracija", "od 500 €"],
  ["Webshop, rezervacijski sustavi i napredne funkcionalnosti", "prema ponudi"],
];

const additionalEn = [
  ["Additional page", "from €80"],
  ["Targeted SEO landing page", "from €100"],
  ["Existing website redesign", "from €400"],
  ["Google Business Profile and basic setup", "from €100"],
  ["Additional content administration", "€40/hour"],
  ["AI chatbot or AI integration", "from €500"],
  ["E-commerce, booking systems, and advanced functionality", "custom quote"],
];

const processHr = [
  ["Kratki razgovor i analiza potreba", "Razumijemo cilj, publiku i funkcionalnosti koje web stvarno treba."],
  ["Dogovor strukture i sadržaja", "Zaključavamo opseg, stranice, materijale i rokove prije izrade."],
  ["Dizajn i izrada", "Gradimo responzivno sučelje u postojećem identitetu ili oblikujemo novi smjer."],
  ["SEO, testiranje i objava", "Uređujemo tehnički SEO, mjerimo brzinu i provjeravamo ključne korisničke tokove."],
  ["Opcionalno održavanje", "Nakon predaje birate želite li samostalno upravljati webom ili ugovoriti podršku."],
];

const processEn = [
  ["Short conversation and needs analysis", "We clarify the goal, audience, and functionality the website genuinely needs."],
  ["Structure and content agreement", "We lock the scope, pages, supplied materials, and timeline before development."],
  ["Design and development", "We build a responsive interface within your identity or define a new direction."],
  ["SEO, testing, and launch", "We configure technical SEO, measure speed, and verify the main user journeys."],
  ["Optional maintenance", "After handover, you can manage the website yourself or choose an annual support plan."],
];

const featuredHr = {
  title: "Auto Gubić",
  category: "Web Pro · dizajn · razvoj · napredni SEO",
  description: "Moderna web-stranica za specijalizirani Volvo servis u Zagrebu, izrađena s fokusom na lokalni SEO, jasno predstavljanje usluga i jednostavno slanje servisnog upita.",
  highlights: [
    "moderna responzivna web-stranica",
    "glavna stranica i ciljane SEO podstranice",
    "tri SEO landing stranice za ključne servisne usluge",
    "napredna tehnička i on-page SEO optimizacija",
    "lokalni SEO za Volvo servis u Zagrebu",
    "prilagođeni servisni obrazac s Volvo modelom, kilometražom i VIN brojem",
    "strukturirani WhatsApp ili e-mail upit",
    "galerija, FAQ, Google karta, pravne informacije i kontakt",
  ],
  href: "https://autogubic.hr/",
  cta: "Pogledaj projekt",
  imageSrc: null,
};

const featuredEn = {
  title: "Auto Gubić",
  category: "Web Pro · design · development · advanced SEO",
  description: "A modern website for a specialized Volvo service center in Zagreb, built around local SEO, clear service presentation, and a simple service inquiry flow.",
  highlights: [
    "modern responsive website",
    "homepage and targeted SEO pages",
    "three SEO landing pages for key service categories",
    "advanced technical and on-page SEO optimization",
    "local SEO for Volvo service in Zagreb",
    "custom service form with Volvo model, mileage, and VIN",
    "structured WhatsApp or email inquiry",
    "gallery, FAQ, Google map, legal information, and contact details",
  ],
  href: "https://autogubic.hr/",
  cta: "View project",
  imageSrc: null,
};

export const webOfferContent = {
  hr: {
    buildPackages: buildPackagesHr,
    maintenancePackages: maintenanceHr,
    additionalServices: additionalHr,
    processSteps: processHr,
    featuredProjects: [featuredHr],
  },
  en: {
    buildPackages: buildPackagesEn,
    maintenancePackages: maintenanceEn,
    additionalServices: additionalEn,
    processSteps: processEn,
    featuredProjects: [featuredEn],
  },
};

export function formatOfferPrice(price, lang = "hr") {
  return lang === "hr" ? `${price} €` : `€${price}`;
}
